{% extends "Layout.phtml" %}

{% block content %}
    <h2>Página de Contato</h2>
    
        {{ message('message_email') | raw }}

    <form action="/contacts/send" method="POST">
        
        <label for="name">Nome:</label>
        {{ message('name') }}
            <input id="name" name="name" type="text">
        <label for="email">email:</label>
        {{ message('email') }}
            <input id="email" name="email" type="text">
        <label for="message">Mensagem:</label>  
        {{ message('message') }}
            <textarea name="message" id="" cols="30" rows="10"></textarea>
            <input id="submit" type="submit" value="Enviar email ">
    </form>

{% endblock %}